---
- name: stop_test_k3s_app
  hosts: k3s
  gather_facts: True

  tasks:
  - name: register service port
    shell:  "kubectl get svc -n {{ project_name }} -o jsonpath='{.items[0].spec.ports[0].nodePort}'"
    register: service_node_port

  - name: write service port to file
    local_action:
      module: shell
      cmd: "echo {{ service_node_port.stdout }} > {{ file_path }}"